export const ADD_ARTICLE = "ADD_ARTICLE"
export const REMOVE_ARTICLE = "REMOVE_ARTICLE"

export const ADD_TASK = "ADD_TASK"
export const COMPLETE_TASK = "COMPLETE_TASK"
export const REMOVE_ONE_TASK = "REMOVE_ONE_TASK"
export const REMOVE_MULTIPLE_TASK = "REMOVE_MULTIPLE_TASK"
export const ADD_MULTIPLE_TASK = "ADD_MULTIPLE_TASK"
export const TOGGLE_ALL = "TOGGLE_ALL"